# Generated by Django 3.2.5 on 2021-07-24 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborapp', '0003_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Bussiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True)),
                ('business_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='neighborapp.profile')),
                ('neighbourhood_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='neighborapp.neighbourhood')),
            ],
        ),
    ]
