# Generated by Django 3.2.5 on 2021-07-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborapp', '0004_auto_20210724_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bussiness',
            old_name='email',
            new_name='business_email',
        ),
        migrations.RemoveField(
            model_name='bussiness',
            name='description',
        ),
    ]
