# Generated by Django 3.2.5 on 2021-07-24 16:09

import cloudinary.models
import datetime
from django.db import migrations
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('neighborapp', '0006_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default=datetime.datetime(2021, 7, 24, 16, 9, 28, 537708, tzinfo=utc), max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
